name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build packages
        run: yarn run build

      - name: Copy README
        run: cp README.md ./dist/ng-select/

      - name: Semantic release
        run: npx semantic-release

      - name: copy @natlex/ng-select version to @natlex/ng-option-highlight
        run: |
          TEMPFILE=$(mktemp)

          jq ".version = $(jq .version ./dist/ng-select/package.json)" \
            ./dist/ng-option-highlight/package.json > "$TEMPFILE"
          mv "$TEMPFILE" ./dist/ng-option-highlight/package.json